AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an ec2 instance which enables SSH
Resources:
  InstanceSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
  MyFirstInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0230bd60aa48260c6
      InstanceType: t2.micro
      KeyName: nihal-aws
      SecurityGroups:
        - !Ref InstanceSecGrp
      Tags:
        - Key: Name
          Value: myfirstinstancecfn


