mykey = "recep2"
ami = "ami-0889a44b331db0194"
region = "us-east-1"
instance_type = "t3a.medium"
jenkins_server_secgr = "phonebook-jenkins-server-secgr"
jenkins-server-tag = "Jenkins Server of Phonebook"
jenkins-profile = "phonebook-jenkins-server-profile"
jenkins-role = "phonebook-jenkins-server-role"